spring:
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
    jdbc-url: ${DB_URL}
  flyway:
    url: ${DB_URL}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
server:
  error:
    include-message: always