spring:
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
    jdbc-url: jdbc:postgresql://localhost:5432/ilaydadastandemo
  flyway:
    url: jdbc:postgresql://localhost:5432/ilaydadastandemo
    user: postgres
    password: postgres
server:
  error:
    include-message: always
